# The following redirect is intended for use with most SPAs that handle
# routing internally.

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://data.mongodb-api.com/app/data-wwiex/endpoint/data/v1/action/insertOne"
    [headers.values]
    Access-Control-Allow-Origin = "*"