[[redirects]]
  from = "https://fancy-narwhal-4896ee.netlify.app"
  to = "https://data.mongodb-api.com/app/data-wwiex/endpoint/data/v1/action/insertOne"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "https://fancy-narwhal-4896ee.netlify.app/signup"
  [headers.values]
    Access-Control-Allow-Origin = "*"